// const apiBaseUrl = (!process.env.NODE_ENV || process.env.NODE_ENV === 'development') ? "http://localhost:8000/api" : "https://hages.dk/ditqapi/public/api"
const apiBaseUrl = "https://api.alquranarabia.com/api"

const metaMapping = [
    {
        localizationCode: 'vn',
        translationCode: 'vietnamese_hassan',
        availableTranslations: [
          {
              code: 'vietnamese_hassan',
              name: 'Hasan Abdul-Karim'
          },
          {
              code: 'vietnamese_rwwad',
              name: 'Ruwwad Translation Center'
          }
        ],
        domain: 'quran.vn',
        country: 'Vietnam',
        metaTitle: 'Quran.vn',
        metaDescription: 'Quran application in Vietnamese',
        quranInLocal: 'Kinh Quran',
        language: 'Vietnamese',
        bannerBackground: 'linear-gradient(90deg,#e80013 0,#fce802 50%,#fce802 50%,#e80013 100%)',
        translationFont: {
            family: 'PalatinoLinotype',
            size: 18,
        },
        logoWidthWeb: 122,
        content: {
            what_is_quran: {
                title: "Kinh Quran là gì?",
            },
            is_quran_god_word: {
                title: "Kinh Quran có phải là lời nói của Thượng Đế không?",
            },
            why_should_read_quran: {
                title: "Tại sao chúng ta phải nên đọc Kinh Quran?",
            },
        },
    },
    {
        localizationCode: 'kh',
        translationCode: 'khmer_cambodia',
        domain: 'QuranKh.com',
        country: 'Cambodia',
        metaTitle: 'QuranKh.com',
        metaDescription: 'Quran application in Khmer',
        quranInLocal: '', // todo
        language: 'Khmer',
        bannerBackground: 'linear-gradient(90deg,#032ea1 0,#e00025 50%,#e00025 50%,#032ea1 100%)',
        translationFont: {
            family: 'Roboto',
            size: 18,
        },
        logoWidthWeb: 182,
        content: {
            what_is_quran: {
                title: "តើគម្ពីគូរ៉ានគឺជាអ្វី?",
            },
            is_quran_god_word: {
                title: "តើគម្ពីគូរ៉ាគឺជាព្រះបន្ទូលរបស់ព្រះ?",
            },
            why_should_read_quran: {
                title: "ហេតុអ្វីបានជាអ្នកគួរអានគម្ពីគូរ៉ា?",
            },
        },
    },
    {
        localizationCode: 'kr',
        translationCode: 'korean_hamid',
        domain: 'Quran.kr',
        country: 'Korea',
        metaTitle: 'Quran.kr',
        metaDescription: 'Quran application in Korean',
        quranInLocal: '', // todo
        language: 'Korean',
        bannerBackground: 'linear-gradient(90deg,#2c569b 0,#cfcfcf 50%,#cfcfcf 50%,#ed1c27 100%)',
        translationFont: {
            family: 'Roboto',
            size: 18,
        },
        logoWidthWeb: 122,
        content: {
            what_is_quran: {
                title: "꾸란이란 무엇인가?",
            },
            is_quran_god_word: {
                title: "꾸란은 하나님의 말씀인가?",
            },
            why_should_read_quran: {
                title: "꾸란을 꼭 읽어야 하는 이유는 무엇인가?",
            },
        },
    },
    {
        localizationCode: 'cn',
        translationCode: 'chinese_makin',
        domain: 'Quran.cn',
        country: 'China',
        metaTitle: 'Quran.cn',
        metaDescription: 'Quran application in Chinese',
        quranInLocal: '', // todo
        language: 'Chinese',
        bannerBackground: 'linear-gradient(90deg, #e80013 0,#e3d210 50%,#e3d210 50%,#e80013 100%)',
        translationFont: {
            family: 'Roboto',
            size: 18,
        },
        logoWidthWeb: 122,
        content: {
            what_is_quran: {
                title: "什么是《古兰经》？",
            },
            is_quran_god_word: {
                title: "《古兰经》是真主的话吗？",
            },
            why_should_read_quran: {
                title: "为什么要读《古兰经》？",
            },
        },
    },
    {
        localizationCode: 'jp',
        translationCode: 'japanese_saeedsato',
        domain: 'Quran.jp',
        country: 'Japan',
        metaTitle: 'Quran.jp',
        metaDescription: 'Quran application in Japanese',
        quranInLocal: '', // todo
        language: 'Japanese',
        bannerBackground: 'linear-gradient(90deg,#eaeaea 0,#bd0028 50%,#bd0028 50%,#eaeaea 100%)',
        translationFont: {
            family: 'Roboto',
            size: 18,
        },
        logoWidthWeb: 122,
        content: {
            what_is_quran: {
                title: "コーランとは何ですか?",
            },
            is_quran_god_word: {
                title: "コーランは神の言葉ですか?",
            },
            why_should_read_quran: {
                title: "なぜコーランを読む必要があるのですか?",
            },
        },
    },
    {
        localizationCode: 'dk',
        translationCode: 'dan-hadiabdollahian',
        domain: 'Quran.dk',
        country: 'Denmark',
        metaTitle: 'Quran.dk',
        metaDescription: 'Quran application in Danish',
        quranInLocal: '', // todo
        language: 'Danish',
        bannerBackground: 'linear-gradient(90deg, #ca072a 0,#d2cece 50%,#d2cece 50%,#ca072a 100%)',
        translationFont: {
            family: 'Roboto',
            size: 18,
        },
        logoWidthWeb: 128,
        content: {
            what_is_quran: {
                title: "Hvad er Koranen?",
            },
            is_quran_god_word: {
                title: "Er Koranen Guds ord?",
            },
            why_should_read_quran: {
                title: "Hvorfor skal man læse Koranen?",
            },
        },
    },
    {
        localizationCode: 'ph',
        translationCode: 'tagalog_rwwad',
        domain: 'Quran.ph',
        country: 'Philippines',
        metaTitle: 'Quran.ph',
        metaDescription: 'Quran application in Filipinos',
        quranInLocal: '', // todo
        language: 'Filipinos',
        bannerBackground: 'linear-gradient(0deg, #0a2165 0,#dfdcc5 50%,#dfdcc5 50%,#bd0a3c 100%)',
        translationFont: {
            family: 'Roboto',
            size: 18,
        },
        logoWidthWeb: 122,
        content: {
            what_is_quran: {
                title: "Ano ang Quran?",
            },
            is_quran_god_word: {
                title: "Ang Quran ba ay salita ng Diyos?",
            },
            why_should_read_quran: {
                title: "Bakit dapat basahin ang Quran?",
            },
        },
    },
    {
        localizationCode: 'fr',
        translationCode: 'french_rashid',
        domain: 'QuranFr.com',
        country: 'France',
        metaTitle: 'QuranFr.com',
        metaDescription: 'Quran application in French',
        quranInLocal: '', // todo
        language: 'French',
        bannerBackground: 'linear-gradient(90deg, #082153 0,#d1cfcf 50%,#d1cfcf 50%,#d00821 100%)',
        translationFont: {
            family: 'Roboto',
            size: 18,
        },
        logoWidthWeb: 172,
        content: {
            what_is_quran: {
                title: "Qu'est-ce que le Coran?",
            },
            is_quran_god_word: {
                title: "Le Coran est-il la parole de Dieu?",
            },
            why_should_read_quran: {
                title: "Pourquoi faut-il lire le Coran?",
            },
        },
    },
    {
        localizationCode: 'de',
        translationCode: 'german_bubenheim',
        domain: 'QuranDe.com',
        country: 'Germany',
        metaTitle: 'QuranDe.com',
        metaDescription: 'Quran application in German',
        quranInLocal: '', // todo
        language: 'German',
        bannerBackground: 'linear-gradient(90deg,#000000 0,#de0000 50%,#de0000 50%,#facf06 100%)',
        translationFont: {
            family: 'Roboto',
            size: 18,
        },
        logoWidthWeb: 182,
        content: {
            what_is_quran: {
                title: "Was ist der Koran?",
            },
            is_quran_god_word: {
                title: "Ist der Koran Gottes Wort?",
            },
            why_should_read_quran: {
                title: "Warum sollte man den Koran lesen?",
            },
        },
    },
];

const localizationCode = process.env.NEXT_PUBLIC_LOCALIZATION_CODE;
const metaInfo = metaMapping?.find(({ localizationCode: l }) => l === localizationCode);

export const server = (!process.env.NODE_ENV || process.env.NODE_ENV === 'development') ? "http://localhost:3000" : `https://www.${metaInfo?.domain}`

export const config = {
    apiBaseUrl,
    localizationCode,
    ...metaInfo,

    appId: process.env.APP_ID,
}




const translations = {
  vn: {
    'Go To Verse': 'Đến câu',
    'Bookmarks': 'Đánh dấu',
    'Pin': 'Ghim',
    'Last Read': 'Đọc lần cuối',
    'Translation by': 'Bản dịch của',
    'Change': 'Thay đổi',
    'Subjective': 'Chủ đề',
    'Chapter List': 'Danh sách chương',
    'Download': 'Tải xuống',
    'Names of Allah': '99 tên Allah',
    'Settings': 'Cài đặt',
    'Install App': 'Cài đặt ứng dụng',
    'About': 'Giới thiệu',
    'Donate': 'Quyên góp',
    'Chapters': 'Chương',
    'Search': 'Tìm kiếm',
    'Home': 'Trang chủ',
    'Bookmarks and Pin': 'Đánh dấu và ghim',
    'Translation': 'Bản dịch',
    'Choose Translation': 'Chọn bản dịch',
    'View': 'Hiển thị',
    'Arabic': 'Tiếng Ả Rập',
    'Footnotes': 'Chú thích',
    'Font Size': 'Cỡ chữ',
    'Font Family': 'Phông chữ',
    'Choose Arabic Font': 'Chọn phông tiếng Ả Rập',
    'Choose Translation Font': 'Chọn phông bản dịch',
    'Theme': 'Giao diện',
    'Change your app setting.': 'Thay đổi cài đặt ứng dụng.',
    'Choose theme': 'Chọn giao diện',
    'All Rights Reserved': 'Mọi quyền được bảo lưu',
    'Powered By': 'Được cung cấp bởi',
    'Grateful': 'Tri ân',
    'Contact': 'Liên hệ',
    'Chapters': 'Chương',
    'Search by title...': 'Tìm chủ đề...',
    'Search Chapter': 'Tìm kiếm chương',
    'Favorites': 'Ưa thích',
    'App installation process for': 'Quá trình cài đặt ứng dụng cho',
    'Open Google Chrome browser and visit': 'Mở trình duyệt Google Chrome và truy cập',
    'Click on top-right "three dots" icon. (If you see popup "Add': 'Nhấp vào biểu tượng "ba chấm" ở trên cùng bên phải. (Nếu bạn thấy cửa sổ bật lên "Thêm',
    'to Home Screen" then click on it.': 'vào Màn hình chính" rồi nhấp vào đó.',
    'Click on "Install app". (If you don’t see "Install app" then wait a few seconds and try again.)': 'Nhấp vào "Cài đặt ứng dụng". (Nếu bạn không thấy "Cài đặt ứng dụng", hãy đợi vài giây và thử lại).',
    'Click on "Install" to confirm.': 'Nhấp vào "Cài đặt" để xác nhận.',
    'Open Safari browser and visit': 'Mở trình duyệt Safari và truy cập',
    'Click on "Share" icon.': 'Nhấp vào biểu tượng "Chia sẻ".',
    'Scroll to bottom and click on "Add to Home Screen".': 'Cuộn xuống dưới cùng và nhấp vào "Thêm vào Màn hình chính".',
    'Click on "Add" to confirm.': 'Nhấp vào "Thêm" để xác nhận.',
    'By the grace of almighty Allah, extremely thankful to Quran Encyclopedia for providing authentic data to spread the message of Allah.': 'Nhờ ơn của Allah toàn năng, tôi vô cùng biết ơn Bách khoa toàn thư Quran đã cung cấp dữ liệu xác thực để truyền bá thông điệp của Allah.',
    'For any inquiries, please email us. We\'ll get back to you as soon as we can, In\'Sha  Allah.': 'Nếu có bất kỳ thắc mắc nào, vui lòng gửi email cho chúng tôi. Chúng tôi sẽ trả lời bạn sớm nhất có thể, In\'Sha Allah.',
    'Quran application in': 'Ứng dụng Quran trong',
    'Developed and maintain by': 'Được phát triển và duy trì bởi',
    'Deeni Info Tech is a non-profit Software Development organization to spread the message of Islam worldwide.': 'Deeni Info Tech là một tổ chức phát triển phần mềm phi lợi nhuận nhằm truyền bá thông điệp Hồi giáo trên toàn thế giới.',
    'Deeni Info Tech working for the following three sets of goals:': 'Deeni Info Tech hoạt động hướng tới ba mục tiêu sau:',
    'Applications for Scholars & Da\'wah organizations': 'Đơn xin học bổng cho các tổ chức Học giả & Da\'wah',
    'Applications for Non-Muslim Countries': 'Ứng dụng cho các quốc gia không theo đạo Hồi',
    'Develop Islamic applications': 'Phát triển các ứng dụng Hồi giáo',
    'The primary goal of Deeni Info Tech is to create more promising Islamic applications. All our applications is/will be free of charge and entirely ad-free.': 'Mục tiêu chính của Deeni Info Tech là tạo ra nhiều ứng dụng Hồi giáo triển vọng hơn. Tất cả các ứng dụng của chúng tôi đều/sẽ miễn phí và hoàn toàn không có quảng cáo.',
    'Please mail us if you want to support. Any kind of support is highly appreciable.': 'Vui lòng gửi email cho chúng tôi nếu bạn muốn hỗ trợ. Bất kỳ sự hỗ trợ nào cũng đều được trân trọng.',
    'Bookmark': 'Đánh dấu trang',
    '99 Names of Allah': '99 Tên của Allah',
    'Go To': 'Đi đến',
    'Download audio and pdf': 'Tải xuống âm thanh và pdf',
    'Search by name...': 'Tìm kiếm theo tên...',
    'Website': 'Trang web',
    'Select chapter and verse': 'Chọn chương và câu',
    'Chapter': 'Chương',
    'Subjective': 'Chủ quan',
    'Email': 'E-mail',
    'Note': 'Lưu ý',
    'Reset': 'Đặt lại',
    'If you remove storage or cache then your settings will be reset to default.': 
      'Nếu bạn xóa bộ nhớ hoặc bộ nhớ cache thì cài đặt của bạn sẽ được đặt lại về mặc định.'
  },
  // en: {
  //   'Go To Verse': 'Go To Verse',
  //   'Bookmarks': 'Bookmarks',
  //   'Pin': 'Pin',
  //   'Last Read': 'Last Read',
  //   'Translation by': 'Translation by',
  //   'Change': 'Change',
  //   'Subjective': 'Subjective',
  //   'Chapter List': 'Chapter List',
  //   'Download': 'Download',
  //   'Names of Allah': 'Names of Allah',
  //   'Settings': 'Settings',
  //   'Install App': 'Install App',
  //   'About': 'About',
  //   'Donate': 'Donate',
  //   'Chapters': 'Chapters',
  //   'Search': 'Search',
  //   'Home': 'Home',
  //   'Bookmarks and Pin': 'Bookmarks and Pin',
  //   'Translation': 'Translation',
  //   'Choose Translation': 'Choose Translation',
  //   'View': 'View',
  //   'Arabic': 'Arabic',
  //   'Footnotes': 'Footnotes',
  //   'Font Size': 'Font Size',
  //   'Font Family': 'Font Family',
  //   'Choose Arabic Font': 'Choose Arabic Font',
  //   'Choose Translation Font': 'Choose Translation Font',
  //   'Theme': 'Theme',
  //   'Change your app setting.': 'Change your app setting.',
  //   'Choose theme': 'Choose theme',
  //   'Note': 'Note',
  //   'Reset': 'Reset',
  //   'If you remove storage or cache then your settings will be reset to default.': 
  //     'If you remove storage or cache then your settings will be reset to default.'
  // },
  // kh: {
  //   'Go To Verse': 'ទៅកាន់ខគម្ពីរ',
  //   'Bookmarks': 'ចំណាំ',
  //   'Pin': 'ខ្ទាស់',
  //   'Last Read': 'អានចុងក្រោយ',
  //   'Translation by': 'ការបកប្រែដោយ',
  //   'Change': 'ផ្លាស់ប្តូរ',
  //   'Subjective': 'ប្រធានបទ',
  //   'Chapter List': 'បញ្ជីជំពូក',
  //   'Download': 'ទាញយក',
  //   'Names of Allah': '៩៩ ព្រះនាមអល់ឡោះ',
  //   'Settings': 'ការកំណត់',
  //   'Install App': 'ដំឡើងកម្មវិធី',
  //   'About': 'អំពី',
  //   'Donate': 'ឧបត្ថម្ភ',
  //   'Chapters': 'ជំពូក',
  //   'Search': 'ស្វែងរក',
  //   'Home': 'ទំព័រដើម',
  //   'Bookmarks and Pin': 'ចំណាំ និងខ្ទាស់',
  //   'Translation': 'ការបកប្រែ',
  //   'Choose Translation': 'ជ្រើសរើសការបកប្រែ',
  //   'View': 'ទិដ្ឋភាព',
  //   'Arabic': 'អារ៉ាប់',
  //   'Footnotes': 'ចំណាំជើងទំព័រ',
  //   'Font Size': 'ទំហំអក្សរ',
  //   'Font Family': 'គ្រួសារអក្សរ',
  //   'Choose Arabic Font': 'ជ្រើសរើសពុម្ពអក្សរអារ៉ាប់',
  //   'Choose Translation Font': 'ជ្រើសរើសពុម្ពអក្សរបកប្រែ',
  //   'Theme': 'រូបរាង',
  //   'Change your app setting.': 'ផ្លាស់ប្តូរការកំណត់កម្មវិធីរបស់អ្នក។',
  //   'Choose theme': 'ជ្រើសរើសរូបរាង',
  //   'Note': 'ចំណាំ',
  //   'Reset': 'កំណត់ឡើងវិញ',
  //   'If you remove storage or cache then your settings will be reset to default.':
  //     'ប្រសិនបើអ្នកយកឃ្លាំងឬឃ្លាំងសំណាកចេញ នោះការកំណត់របស់អ្នកនឹងត្រូវបានកំណត់ឡើងវិញទៅជាលំនាំដើម។'
  // },
  // kr: {
  //   'Go To Verse': '구절로 이동',
  //   'Bookmarks': '북마크',
  //   'Pin': '고정',
  //   'Last Read': '마지막 읽음',
  //   'Translation by': '번역자',
  //   'Change': '변경',
  //   'Subjective': '주제별',
  //   'Chapter List': '장 목록',
  //   'Download': '다운로드',
  //   'Names of Allah': '알라의 99개의 이름',
  //   'Settings': '설정',
  //   'Install App': '앱 설치',
  //   'About': '정보',
  //   'Donate': '기부',
  //   'Chapters': '장',
  //   'Search': '검색',
  //   'Home': '홈',
  //   'Bookmarks and Pin': '북마크 및 고정',
  //   'Translation': '번역',
  //   'Choose Translation': '번역 선택',
  //   'View': '보기',
  //   'Arabic': '아랍어',
  //   'Footnotes': '각주',
  //   'Font Size': '글꼴 크기',
  //   'Font Family': '글꼴',
  //   'Choose Arabic Font': '아랍어 글꼴 선택',
  //   'Choose Translation Font': '번역 글꼴 선택',
  //   'Theme': '테마',
  //   'Change your app setting.': '앱 설정을 변경하세요.',
  //   'Choose theme': '테마 선택',
  //   'Note': '참고',
  //   'Reset': '초기화',
  //   'If you remove storage or cache then your settings will be reset to default.':
  //     '저장소나 캐시를 제거하면 설정이 기본값으로 초기화됩니다.'
  // },
  // cn: {
  //   'Go To Verse': '转到经文',
  //   'Bookmarks': '书签',
  //   'Pin': '固定',
  //   'Last Read': '最后阅读',
  //   'Translation by': '翻译者',
  //   'Change': '更改',
  //   'Subjective': '主题',
  //   'Chapter List': '章节列表',
  //   'Download': '下载',
  //   'Names of Allah': '安拉的99个尊名',
  //   'Settings': '设置',
  //   'Install App': '安装应用',
  //   'About': '关于',
  //   'Donate': '捐赠',
  //   'Chapters': '章节',
  //   'Search': '搜索',
  //   'Home': '首页',
  //   'Bookmarks and Pin': '书签和固定',
  //   'Translation': '翻译',
  //   'Choose Translation': '选择翻译',
  //   'View': '视图',
  //   'Arabic': '阿拉伯语',
  //   'Footnotes': '脚注',
  //   'Font Size': '字体大小',
  //   'Font Family': '字体',
  //   'Choose Arabic Font': '选择阿拉伯字体',
  //   'Choose Translation Font': '选择翻译字体',
  //   'Theme': '主题',
  //   'Change your app setting.': '更改您的应用设置。',
  //   'Choose theme': '选择主题',
  //   'Note': '注意',
  //   'Reset': '重置',
  //   'If you remove storage or cache then your settings will be reset to default.':
  //     '如果您删除存储或缓存，您的设置将重置为默认值。'
  // },
  // jp: {
  //   'Go To Verse': '節に移動',
  //   'Bookmarks': 'ブックマーク',
  //   'Pin': 'ピン留め',
  //   'Last Read': '最後に読んだ',
  //   'Translation by': '翻訳者',
  //   'Change': '変更',
  //   'Subjective': '主題別',
  //   'Chapter List': '章のリスト',
  //   'Download': 'ダウンロード',
  //   'Names of Allah': 'アッラーの99の名前',
  //   'Settings': '設定',
  //   'Install App': 'アプリをインストール',
  //   'About': 'について',
  //   'Donate': '寄付',
  //   'Chapters': '章',
  //   'Search': '検索',
  //   'Home': 'ホーム',
  //   'Bookmarks and Pin': 'ブックマークとピン',
  //   'Translation': '翻訳',
  //   'Choose Translation': '翻訳を選択',
  //   'View': '表示',
  //   'Arabic': 'アラビア語',
  //   'Footnotes': '脚注',
  //   'Font Size': 'フォントサイズ',
  //   'Font Family': 'フォント',
  //   'Choose Arabic Font': 'アラビア語フォントを選択',
  //   'Choose Translation Font': '翻訳フォントを選択',
  //   'Theme': 'テーマ',
  //   'Change your app setting.': 'アプリの設定を変更します。',
  //   'Choose theme': 'テーマを選択',
  //   'Note': '注意',
  //   'Reset': 'リセット',
  //   'If you remove storage or cache then your settings will be reset to default.':
  //     'ストレージまたはキャッシュを削除すると、設定はデフォルトにリセットされます。'
  // },
  // dk: {
  //   'Go To Verse': 'Gå til vers',
  //   'Bookmarks': 'Bogmærker',
  //   'Pin': 'Fastgør',
  //   'Last Read': 'Sidst læst',
  //   'Translation by': 'Oversat af',
  //   'Change': 'Ændre',
  //   'Subjective': 'Emner',
  //   'Chapter List': 'Kapitelliste',
  //   'Download': 'Download',
  //   'Names of Allah': 'Allahs 99 navne',
  //   'Settings': 'Indstillinger',
  //   'Install App': 'Installer app',
  //   'About': 'Om',
  //   'Donate': 'Doner',
  //   'Chapters': 'Kapitler',
  //   'Search': 'Søg',
  //   'Home': 'Hjem',
  //   'Bookmarks and Pin': 'Bogmærker og fastgørelse',
  //   'Translation': 'Oversættelse',
  //   'Choose Translation': 'Vælg oversættelse',
  //   'View': 'Visning',
  //   'Arabic': 'Arabisk',
  //   'Footnotes': 'Fodnoter',
  //   'Font Size': 'Skriftstørrelse',
  //   'Font Family': 'Skrifttype',
  //   'Choose Arabic Font': 'Vælg arabisk skrifttype',
  //   'Choose Translation Font': 'Vælg oversættelsesskrifttype',
  //   'Theme': 'Tema',
  //   'Change your app setting.': 'Ændre din app-indstilling.',
  //   'Choose theme': 'Vælg tema',
  //   'Note': 'Bemærk',
  //   'Reset': 'Nulstil',
  //   'If you remove storage or cache then your settings will be reset to default.':
  //     'Hvis du fjerner lager eller cache, vil dine indstillinger blive nulstillet til standard.'
  // },
  // ph: {
  //   'Go To Verse': 'Pumunta sa Talata',
  //   'Bookmarks': 'Mga Bookmark',
  //   'Pin': 'I-pin',
  //   'Last Read': 'Huling Binasa',
  //   'Translation by': 'Salin ni',
  //   'Change': 'Palitan',
  //   'Subjective': 'Paksa',
  //   'Chapter List': 'Listahan ng Kabanata',
  //   'Download': 'I-download',
  //   'Names of Allah': '99 Ngalan ng Allah',
  //   'Settings': 'Mga Setting',
  //   'Install App': 'I-install ang App',
  //   'About': 'Tungkol',
  //   'Donate': 'Mag-donate',
  //   'Chapters': 'Mga Kabanata',
  //   'Search': 'Maghanap',
  //   'Home': 'Home',
  //   'Bookmarks and Pin': 'Mga Bookmark at Pin',
  //   'Translation': 'Pagsasalin',
  //   'Choose Translation': 'Pumili ng Salin',
  //   'View': 'Tingnan',
  //   'Arabic': 'Arabe',
  //   'Footnotes': 'Mga Talababa',
  //   'Font Size': 'Laki ng Font',
  //   'Font Family': 'Pamilya ng Font',
  //   'Choose Arabic Font': 'Pumili ng Arabic Font',
  //   'Choose Translation Font': 'Pumili ng Translation Font',
  //   'Theme': 'Tema',
  //   'Change your app setting.': 'Baguhin ang setting ng iyong app.',
  //   'Choose theme': 'Pumili ng tema',
  //   'Note': 'Paalala',
  //   'Reset': 'I-reset',
  //   'If you remove storage or cache then your settings will be reset to default.':
  //     'Kung tatanggalin mo ang storage o cache, ang iyong mga setting ay maa-reset sa default.'
  // },
  // fr: {
  //   'Go To Verse': 'Aller au verset',
  //   'Bookmarks': 'Favoris',
  //   'Pin': 'Épingler',
  //   'Last Read': 'Dernière lecture',
  //   'Translation by': 'Traduit par',
  //   'Change': 'Changer',
  //   'Subjective': 'Sujets',
  //   'Chapter List': 'Liste des chapitres',
  //   'Download': 'Télécharger',
  //   'Names of Allah': 'Les 99 noms d\'Allah',
  //   'Settings': 'Paramètres',
  //   'Install App': 'Installer l\'application',
  //   'About': 'À propos',
  //   'Donate': 'Faire un don',
  //   'Chapters': 'Chapitres',
  //   'Search': 'Recherche',
  //   'Home': 'Accueil',
  //   'Bookmarks and Pin': 'Favoris et épingles',
  //   'Translation': 'Traduction',
  //   'Choose Translation': 'Choisir la traduction',
  //   'View': 'Vue',
  //   'Arabic': 'Arabe',
  //   'Footnotes': 'Notes de bas de page',
  //   'Font Size': 'Taille de police',
  //   'Font Family': 'Police',
  //   'Choose Arabic Font': 'Choisir la police arabe',
  //   'Choose Translation Font': 'Choisir la police de traduction',
  //   'Theme': 'Thème',
  //   'Change your app setting.': 'Modifier les paramètres de votre application.',
  //   'Choose theme': 'Choisir un thème',
  //   'Note': 'Remarque',
  //   'Reset': 'Réinitialiser',
  //   'If you remove storage or cache then your settings will be reset to default.':
  //     'Si vous supprimez le stockage ou le cache, vos paramètres seront réinitialisés par défaut.'
  // },
  // de: {
  //   'Go To Verse': 'Zu Vers gehen',
  //   'Bookmarks': 'Lesezeichen',
  //   'Pin': 'Anheften',
  //   'Last Read': 'Zuletzt gelesen',
  //   'Translation by': 'Übersetzt von',
  //   'Change': 'Ändern',
  //   'Subjective': 'Themen',
  //   'Chapter List': 'Kapitelliste',
  //   'Download': 'Herunterladen',
  //   'Names of Allah': 'Die 99 Namen Allahs',
  //   'Settings': 'Einstellungen',
  //   'Install App': 'App installieren',
  //   'About': 'Über',
  //   'Donate': 'Spenden',
  //   'Chapters': 'Kapitel',
  //   'Search': 'Suche',
  //   'Home': 'Startseite',
  //   'Bookmarks and Pin': 'Lesezeichen und Anheften',
  //   'Translation': 'Übersetzung',
  //   'Choose Translation': 'Übersetzung wählen',
  //   'View': 'Ansicht',
  //   'Arabic': 'Arabisch',
  //   'Footnotes': 'Fußnoten',
  //   'Font Size': 'Schriftgröße',
  //   'Font Family': 'Schriftart',
  //   'Choose Arabic Font': 'Arabische Schriftart wählen',
  //   'Choose Translation Font': 'Übersetzungsschriftart wählen',
  //   'Theme': 'Thema',
  //   'Change your app setting.': 'Ändern Sie Ihre App-Einstellungen.',
  //   'Choose theme': 'Thema wählen',
  //   'Note': 'Hinweis',
  //   'Reset': 'Zurücksetzen',
  //   'If you remove storage or cache then your settings will be reset to default.':
  //     'Wenn Sie Speicher oder Cache entfernen, werden Ihre Einstellungen auf die Standardwerte zurückgesetzt.'
  // }
};

export const t = (key) => {
  return translations[config.localizationCode]?.[key] || translations['en'][key] || key;
};

export const getAvailableLanguages = () => {
  return Object.keys(translations).map(code => ({
    code,
    name: translations[code]['Language'] || code.toUpperCase()
  }));
};